### ISSUE TITLE
Sorry the sources?

### ISSUE THREAD

**Issue by dbonino** [nextbreakpoint/flink-client#10]
I was looking at this client, but I cannot find any trace of the library sources in the master branch (the only available). Only tests are available, which are not exactly what an open source project is expected to provide. May be a push is missing?

**Comment by nextbreakpoint** [comment]
Hello, the code is missing because it is generated from the openapi file. When you run the build command, the code is produced and packaged into a library. I could commit the code, you are right, but the actual source is the file flink-openapi.yaml in the root directory.

**Comment by dbonino** [comment]
Ok then this is just the java-client generated by swagger given the open api description of the Flink Monitoring Api, makes sense. Thanks for the clarification.

**Comment by nextbreakpoint** [comment]
Correct, but I added tests to validate the client :)

**Comment by nextbreakpoint** [comment]
Also, Flink project doesn't provide the openapi file, I had to manually create it from the documentation

**Comment by dbonino** [comment]
Yes clear, no doubts on the contribution of this project. Thanks for
sharing it.

Il mer 22 apr 2020, 18:50 NextBreakpoint <notifications@github.com> ha
scritto:
