### ISSUE TITLE
About more subtasks metrics details.

### ISSUE THREAD

**Issue by imperio-wxm** [nextbreakpoint/flink-client#16]
About url `/jobs/:jobid/vertices/:vertexid/subtasks/:subtaskindex/metrics`
I want more metrics info from subtask however the subtask information I get from the client is a simple map.
And metrics are not just `IOMetricsInfo`.

```java
JobIdsWithStatusOverview jobIdsWithStatusOverview = api.getJobs();
        String jobId = jobIdsWithStatusOverview.getJobs().get(0).getId();
        JobDetailsInfo details = api.getJobDetails(jobId);
        details.getVertices().forEach(v -> {
            IOMetricsInfo metricsInfo = v.getMetrics();
            Map<String, Integer> tasks = v.getTasks();
        });
```

![image](https://user-images.githubusercontent.com/8111349/93416369-43107d80-f8d8-11ea-9997-7b3ed772f4bc.png)

More information is not available, as shown in the figure below and kafka related. 

![image](https://user-images.githubusercontent.com/8111349/93416390-56234d80-f8d8-11ea-9b2c-1087aadedc92.png)

**Comment by nextbreakpoint** [comment]
Thank you for reporting the issue. I'll have a look, and see how I can fix it

**Comment by nextbreakpoint** [comment]
Which version of Flink are you using?

**Comment by imperio-wxm** [comment]
@nextbreakpoint 
Hi, my flink version is 1.8

**Comment by andreamedeghini-lh** [comment]
The method api.getJobDetails() returns vertices with metrics, but the metrics are defined as IOMetricsInfo in the Flink REST API (see https://ci.apache.org/projects/flink/flink-docs-stable/monitoring/rest_api.html#jobs-jobid). Therefore you have to invoke a different endpoint for getting all vertex's metrics:

Object metrics = api.getJobSubtaskMetrics(jobId, vertexId, 0, null);

The returned object is actually a map. The last argument is the name of a metrics in case you want only one:

Object jobSubtaskMetrics = api.getJobSubtaskMetrics(jobId, vertexId, 0, "numRecordsIn");

The specification of the method getJobSubtaskMetrics() looks like this (from the flink-openapi.yaml file): 

`/jobs/{jobid}/vertices/{vertexid}/subtasks/{subtaskindex}/metrics:
    get:
      tags:
        - flink
      operationId: getJobSubtaskMetrics
      summary: Provides access to subtask metrics
      parameters:
        - name: jobid
          in: path
          description: 32-character hexadecimal string value that identifies a job
          required: true
          schema:
            type: string
        - name: vertexid
          in: path
          description: 32-character hexadecimal string value that identifies a job vertex
          required: true
          schema:
            type: string
        - name: subtaskindex
          in: path
          description: Positive integer value that identifies a subtask
          required: true
          schema:
            type: integer
        - name: get
          in: query
          description: Comma-separated list of string values to select specific metrics
          required: false
          schema:
            type: string
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:
              schema:
                type: object
`

the response type is an object, therefore you should be able to see all the metrics.

**Comment by nextbreakpoint** [comment]
The method api.getJobDetails() returns vertices with metrics, but the metrics are defined as IOMetricsInfo in the Flink REST API (see https://ci.apache.org/projects/flink/flink-docs-stable/monitoring/rest_api.html#jobs-jobid). Therefore you have to invoke a different endpoint for getting all vertex's metrics:

Object metrics = api.getJobSubtaskMetrics(jobId, vertexId, 0, null);

The returned object is actually a map. The last argument is the name of a metrics in case you want only one:

Object jobSubtaskMetrics = api.getJobSubtaskMetrics(jobId, vertexId, 0, "numRecordsIn");

The specification of the method getJobSubtaskMetrics() looks like this (from the flink-openapi.yaml file): 

<pre>
/jobs/{jobid}/vertices/{vertexid}/subtasks/{subtaskindex}/metrics:
    get:
      tags:
        - flink
      operationId: getJobSubtaskMetrics
      summary: Provides access to subtask metrics
      parameters:
        - name: jobid
          in: path
          description: 32-character hexadecimal string value that identifies a job
          required: true
          schema:
            type: string
        - name: vertexid
          in: path
          description: 32-character hexadecimal string value that identifies a job vertex
          required: true
          schema:
            type: string
        - name: subtaskindex
          in: path
          description: Positive integer value that identifies a subtask
          required: true
          schema:
            type: integer
        - name: get
          in: query
          description: Comma-separated list of string values to select specific metrics
          required: false
          schema:
            type: string
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:
              schema:
                type: object
</pre>

the response type is an object, therefore you should be able to see all the metrics.

**Comment by nextbreakpoint** [comment]
@imperio-wxm could you confirm that the suggested solution works?

**Comment by imperio-wxm** [comment]
@nextbreakpoint 
Hi, thanks.
Object jobSubtaskMetrics = api.getJobSubtaskMetrics(jobId, vertexId, 0, "numRecordsIn");
It works!

Still have two question:  

**1. Is FlinkApi thread safe？**
Can i use singleton with FlinkApi.
If not, how should I support concurrent access to multiple app information.

**2. About async wait time**
My main thread has been launched, but there is no result of asynchronous. I can only wait with sleep()
I don't know how long it will take to get the result. How should the callback get the result?

```java
api.getJobCheckpointsAsync(jobId, new ApiCallback<CheckpointingStatistics>() {
    @Override
    public void onFailure(ApiException e, int statusCode, Map<String, List<String>> responseHeaders) {
    }
    @Override
    public void onSuccess(CheckpointingStatistics result, int statusCode, Map<String, List<String>> responseHeaders) {
         // wait result
    }
    @Override
    public void onUploadProgress(long bytesWritten, long contentLength, boolean done) {

    }
    @Override
    public void onDownloadProgress(long bytesRead, long contentLength, boolean done) {

    }
});
```

**Comment by nextbreakpoint** [comment]
> ```java
> api.getJobCheckpointsAsync
> ```

1. FlinkApi depends on ApiClient and ApiClient doesn't look thread safe to me when I look at the implementation.
You should create a new FlinkApi with a new ApiClient for each thread (beware that the default constructor depends a shared instance of ApiClient). You could also check the documentation of okhttp (this is the framework used in the client).

2. The result should be returned in the onSuccess callback. You can use the callback to notify some other thread.

**Comment by imperio-wxm** [comment]
@nextbreakpoint 
Thanks, I got it.
