### ISSUE TITLE
Submit flink-client to flink-packages.org

### ISSUE THREAD

**Issue by rmetzger** [nextbreakpoint/flink-client#3]
flink-packages.org has been launched recently for increased visibility of ecosystem projects. It would be nice if you could submit this package there.

**Comment by nextbreakpoint** [comment]
thanks for the suggestion, I'll do asap

**Comment by nextbreakpoint** [comment]
Submitted
https://flink-packages.org/packages/nextbreakpoint-flink-client

**Comment by rmetzger** [comment]
Cool, thanks a lot :)

**Comment by nextbreakpoint** [comment]
I have submitted my Kubernetes operator for Flink too

**Comment by rmetzger** [comment]
Yeah, I saw that. Very nice & thank you. We've now quite a few k8s connectors in flink-packages :)

**Comment by nextbreakpoint** [comment]
yep, I guess many people felt they needed one :)
