### ISSUE TITLE
about the return value when I call 'runJar' method

### ISSUE THREAD

**Issue by foobarrer** [nextbreakpoint/flink-client#4]
Hello, this project is very helpful for me, but when I call the 'runJar' method, I can't get the return value of JobId which is very important for me, however when I enable the debug mode by call method setDebugging(true), there is jobId in console， like below

{"jobid":"796bae32665baed05232765484e28dff"}

 Now I'm looking for the code that print the jobId, but have not seen anything about it yet. so the question that bother me is why the return value not contains the jobId,? what should I do to get the jobid?
Thanks!

**Comment by nextbreakpoint** [comment]
Give some time, I'll check and come back with an answer

**Comment by nextbreakpoint** [comment]
Could you tell me which version of Flink are you using?

**Comment by nextbreakpoint** [comment]
I confirm that there is an issue in how the response is mapped into a class. The open api specification I have created it has the wrong schema for the runJar response. I am working on a fix, and I'll release a new version soon. 
Thanks for reporting the issue!

**Comment by nextbreakpoint** [comment]
I have fixed the response schema, however it appears that the jobId is not always assigned in the response.

**Comment by nextbreakpoint** [comment]
The issue has been fixed in version 1.0.2
