### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by lubo212** [nextbreakpoint/flink-client#9]
感谢你提供的工具！

**Comment by lubo212** [comment]
我在使用时发现了一些问题，请问下有没有解决方案：
1.我执行uploadJar() 方法：
上传过程中会有一些乱码产生
+��:��org/apache/kafka/common/utils/Utils$1.clasI�zE#�k��LT������darwin/x86_64/liblz4-java.dyli��zE]��<�1�����net/jpountz/lz4/LZ4JavaSafeFastDecompressor.clas��zE�p|b�
�$���#�net/jpountz/lz4/LZ4UnsafeUtils.clas��zEgK5>� 	4���.�net/jpountz/xxhash/StreamingXXHash32JavaUnsafe.clas��zE�|����
)���:�net/jpountz/xxhash/XXHash64JavaSafe.classP��/R�oI���2���A�org/apache/oro/text/regex/StringSubstitution.cla��/e���$O )���C�org/apache/oro/text/awk/AwkCompiler.classPK   ��/���&��'R�org/apache/oro/text/awk/PlusNode.classPK    ��/�}��i&��{S�org/apac��2��W\�com/googlecode/aviator/asm/AnnotationVisitor.clasڌ�?�6��H9���]�com/googlecode/aviator/asm/commons/GeneratorAdapter.clasڌ�?~F\��9���|�com/googlecode/aviator/asm/optimizer/ClassOptimizer.clasڌ�?)~���
��com/googlecode/aviator/asm/signature/SignatureReader.clasڌ�?�M�_z7��A��com/googlecode/aviator/asm/tree/analysis/SmallSet.clasڌ�?�o����2����com/googlecode/aviator/asm/tree/IincInsnNode.clasڌ�?�_K�4d	:��_��com/googlecode/aviator/asm/tree/LookupSwitchInsnNode.clasڌ�?�#�V�4�����com/googlecode/aviator/asm/tree/MethodInsnNode.clasڌ�?��q4	R=�����com/googlecode/aviator/asm/util/ASMifierAbstractVisitor.clasڌ�?��-8��R��com/googlecode/aviator/asm/util/TraceMethodVisitor.clasڌ�?�Bl�@��˴�com/googlecode/aviator/asm/xml/ASMContentHandler$ClassRule.clasڌ�?$����D����com/googlecode/aviator/asm/xml/ASMContentHandler$ExceptionRule.clasڌ�?q%�i��
G�����com/googlecode/aviator/asm/xml/ASMContentHandler$LookupSwitchRule.clasڌ�?#�Ў��?����com/googlecode/aviator/asm/xml/Processor$SingleDocElement.clasڌ�?�ۈM��/��z��com/googlecode/aviator/AviatorEvaluator$1.clasڌ�?��z97/�����com/googlecode/aviator/AviatorEvaluator$2.clasڌ�?MS���kA����com/googlecode/aviator/exception/ExpressionRuntimeException.clasڌ�?[���wE��1��com/googlecode/aviator/exception/ExpressionSyntaxErrorException.clasڌ�?a����.��a��com/googlecode/aviator/LiteralExpression.clasڌ�?��&oB��~��com/googlecode/aviator/runtime/function/math/MathTanFunction.clasڌ�?i�M-v�K��]��com/googlecode/aviator/runtime/function/string/StringEndsWithFunction.clasڌ�?�q ��D��L��com/googlecode/aviator/runtime/function/system/SysDateFunction.clasڌ�?�`P�:�����com/googlecode/aviator/runtime/type/AviatorBoolean$1.clasٌ�?��B�7����com/googlecode/aviator/runtime/type/AviatorObject.clas֌�?�
5��k��META-INF/maven/com.googlecode.aviator/aviator/pom.xmRpi;���9�,�����org/apache/commons/beanutils/BeanUtils.clasRpi;������

这是什么情况呢？

**Comment by nextbreakpoint** [comment]
I am sorry, but I am not sure to understand what is the question. I passed the text in google translator, and I can guess there is a problem with uploadJar, but I need more information. 
Could you provide more context? Or show your code?
